# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.ErrorHandlingTest do
  use ExUnit.Case, async: true

  test "error_empty_language_name" do
    # Parsing with empty language name should error
    assert_raise ErlangError, fn ->
      TreeSitterLanguagePack.get_language_ptr("")
    end
  end

  @tag :skip_unless_javascript
  test "error_handling_empty_source" do
    # Parsing an empty string should still produce a tree.
    unless TreeSitterLanguagePack.has_language("javascript") do
      IO.puts("Skipping: language 'javascript' not available")
    else
    tree = TreeSitterLanguagePack.parse_string("javascript", "")
    assert is_reference(tree), "Parse tree should be a reference"
    end
  end

  @tag :skip_unless_javascript
  test "error_handling_invalid_syntax" do
    # Parsing invalid syntax should produce a tree with error nodes.
    unless TreeSitterLanguagePack.has_language("javascript") do
      IO.puts("Skipping: language 'javascript' not available")
    else
    tree = TreeSitterLanguagePack.parse_string("javascript", "function function function @@@ %%%")
    assert is_reference(tree), "Parse tree should be a reference"
    assert TreeSitterLanguagePack.tree_has_error_nodes(tree), "Tree should contain error nodes"
    end
  end

  test "error_handling_unknown_language" do
    # Loading a nonexistent language should produce an error.
    assert_raise ErlangError, fn ->
      TreeSitterLanguagePack.get_language_ptr("nonexistent_xyz")
    end
  end

end
