// Code generated by e2e-generator. DO NOT EDIT.

package io.github.treesitter.languagepack.e2e;

import io.github.treesitter.languagepack.TsPackRegistry;

/**
 * Shared helpers for E2E tests.
 */
final class Helpers {

    private Helpers() {}

    /**
     * Create a new registry, failing the test if creation fails.
     */
    static TsPackRegistry createRegistry() {
        return new TsPackRegistry();
    }
}
