// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn parsing_javascript_class() {
    if !tree_sitter_language_pack::has_language("javascript") {
        eprintln!("Skipping: language 'javascript' not available");
        return;
    }
    // Parse a JavaScript class declaration.
    let mut parser =
        tree_sitter_language_pack::get_parser("javascript").expect("Failed to get parser for 'javascript'");
    let tree = parser.parse("class Foo { bar() {} }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        root.child_count() >= 1,
        "Root should have at least 1 child(ren), got {}",
        root.child_count()
    );
    assert!(
        e2e_tests::tree_contains_node_type(root, "class_declaration"),
        "Tree should contain a 'class_declaration' node"
    );
}

#[test]
fn parsing_python_function() {
    if !tree_sitter_language_pack::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse a Python function definition.
    let mut parser = tree_sitter_language_pack::get_parser("python").expect("Failed to get parser for 'python'");
    let tree = parser.parse("def hello():\n    pass\n", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        root.child_count() >= 1,
        "Root should have at least 1 child(ren), got {}",
        root.child_count()
    );
    assert!(
        e2e_tests::tree_contains_node_type(root, "function_definition"),
        "Tree should contain a 'function_definition' node"
    );
}

#[test]
fn parsing_rust_struct() {
    if !tree_sitter_language_pack::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Parse a Rust struct definition.
    let mut parser = tree_sitter_language_pack::get_parser("rust").expect("Failed to get parser for 'rust'");
    let tree = parser.parse("struct Point { x: f64, y: f64 }", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(
        root.child_count() >= 1,
        "Root should have at least 1 child(ren), got {}",
        root.child_count()
    );
}
