<?php
// Code generated by e2e-generator. DO NOT EDIT.

declare(strict_types=1);

namespace E2E\Tests;

use PHPUnit\Framework\TestCase;

class ParsingTest extends TestCase
{

    public function test_parsing_javascript_class(): void
    {
        // Parse a JavaScript class declaration.
        if (!\ts_pack_has_language('javascript')) {
            $this->markTestSkipped('Language \'javascript\' not available');
        }
        $langPtr = \ts_pack_get_language('javascript');
        $this->assertIsInt($langPtr, 'Language pointer should be a valid integer handle');
        $sexp = \ts_pack_parse_string('javascript', 'class Foo { bar() {} }');
        $this->assertNotEmpty($sexp, 'Parse tree S-expression should not be empty');
    }

    public function test_parsing_python_function(): void
    {
        // Parse a Python function definition.
        if (!\ts_pack_has_language('python')) {
            $this->markTestSkipped('Language \'python\' not available');
        }
        $langPtr = \ts_pack_get_language('python');
        $this->assertIsInt($langPtr, 'Language pointer should be a valid integer handle');
        $sexp = \ts_pack_parse_string('python', 'def hello():\n    pass\n');
        $this->assertNotEmpty($sexp, 'Parse tree S-expression should not be empty');
    }

    public function test_parsing_rust_struct(): void
    {
        // Parse a Rust struct definition.
        if (!\ts_pack_has_language('rust')) {
            $this->markTestSkipped('Language \'rust\' not available');
        }
        $langPtr = \ts_pack_get_language('rust');
        $this->assertIsInt($langPtr, 'Language pointer should be a valid integer handle');
        $sexp = \ts_pack_parse_string('rust', 'struct Point { x: f64, y: f64 }');
        $this->assertNotEmpty($sexp, 'Parse tree S-expression should not be empty');
    }
}
