// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, process } from "./helpers";

describe("parsing", () => {
  it("parsing_javascript_class", () => {
    // Parse a JavaScript class declaration.
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const ptr = getLanguagePtr("javascript");
    expect(ptr).toBeTruthy();
  });

  it("parsing_python_function", () => {
    // Parse a Python function definition.
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("parsing_rust_struct", () => {
    // Parse a Rust struct definition.
    if (!hasLanguage("rust")) {
      console.log("Skipping: language 'rust' not available");
      return;
    }
    const ptr = getLanguagePtr("rust");
    expect(ptr).toBeTruthy();
  });

});
