// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, process } from "./helpers";

describe("registry", () => {
  it("registry_has_language_false", () => {
    // has_language('nonexistent') should return false.
    expect(hasLanguage("nonexistent")).toBe(false);
  });

  it("registry_has_language_true", () => {
    // has_language('python') should return true.
    expect(hasLanguage("python")).toBe(true);
  });

  it("registry_list_languages", () => {
    // available_languages should return a non-empty list.
    const langs = availableLanguages();
    expect(langs.length).toBeGreaterThan(0);
  });

});
