from typing import TypeAlias

from tree_sitter_language_pack._native import (
    DownloadError,
    LanguageNotFoundError,
    ParseError,
    ProcessConfig,
    QueryError,
    TreeHandle,
    available_languages,
    cache_dir,
    clean_cache,
    configure,
    detect_language,
    download,
    download_all,
    downloaded_languages,
    get_binding,
    get_language,
    get_parser,
    has_language,
    init,
    language_count,
    manifest_languages,
    parse_string,
    process,
)

SupportedLanguage: TypeAlias = str

__all__ = [
    "DownloadError",
    "LanguageNotFoundError",
    "ParseError",
    "ProcessConfig",
    "QueryError",
    "SupportedLanguage",
    "TreeHandle",
    "available_languages",
    "cache_dir",
    "clean_cache",
    "configure",
    "detect_language",
    "download",
    "download_all",
    "downloaded_languages",
    "get_binding",
    "get_language",
    "get_parser",
    "has_language",
    "init",
    "language_count",
    "manifest_languages",
    "parse_string",
    "process",
]
