# Code generated by e2e-generator. DO NOT EDIT.

from tree_sitter_language_pack import (
    available_languages,
    has_language,
)


def test_registry_has_language_false():
    """has_language('nonexistent') should return false."""
    assert has_language("nonexistent") is False, "has_language('nonexistent') should be false"


def test_registry_has_language_true():
    """has_language('python') should return true."""
    assert has_language("python") is True, "has_language('python') should be true"


def test_registry_list_languages():
    """available_languages should return a non-empty list."""
    langs = available_languages()
    assert len(langs) > 0, "available_languages() should not be empty"
