# Code generated by e2e-generator. DO NOT EDIT.

import pytest
from tree_sitter_language_pack import (
    get_parser,
    has_language,
)


@pytest.mark.skipif(not has_language("go"), reason="Language 'go' not available")
def test_go_function_metadata():
    """Intel: extract structure from Go function definition"""
    parser = get_parser("go")
    tree = parser.parse(b"package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n")


@pytest.mark.skipif(not has_language("javascript"), reason="Language 'javascript' not available")
def test_javascript_multi_import_metadata():
    """Intel: detect multiple imports and function in JavaScript"""
    parser = get_parser("javascript")
    tree = parser.parse(b"import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n")


@pytest.mark.skipif(not has_language("javascript"), reason="Language 'javascript' not available")
def test_meta_javascript_exports_detail():
    """JavaScript with exports, verify export count"""
    parser = get_parser("javascript")
    tree = parser.parse(b"export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_meta_python_comments():
    """Python with comments, verify comment count"""
    parser = get_parser("python")
    tree = parser.parse(b"# This is a comment\n# Another comment\ndef hello():\n    # inline comment\n    pass\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_meta_python_imports_detail():
    """Python with multiple imports, verify imports contain specific source"""
    parser = get_parser("python")
    tree = parser.parse(b"import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_meta_python_metrics_detail():
    """Python code with metrics assertions"""
    parser = get_parser("python")
    tree = parser.parse(b"# module docstring\nimport os\n\ndef hello():\n    # greeting\n    print('hello')\n\ndef world():\n    print('world')\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("rust"), reason="Language 'rust' not available")
def test_meta_rust_structure_name():
    """Rust struct with name, verify structure name contains value"""
    parser = get_parser("rust")
    tree = parser.parse(b"pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_chunking_metadata():
    """Intel: chunk multi-function Python source into multiple pieces"""
    parser = get_parser("python")
    tree = parser.parse(b"def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_class_with_methods_metadata():
    """Intel: extract nested structure from Python class with methods"""
    parser = get_parser("python")
    tree = parser.parse(b"class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n")


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_function_metadata():
    """Intel: extract structure from Python function definition"""
    parser = get_parser("python")
    tree = parser.parse(b"def greet(name):\n    return f'Hello, {name}!'\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_malformed_code_metadata():
    """Intel: detect diagnostics in malformed Python code"""
    parser = get_parser("python")
    tree = parser.parse(b"def broken(\n    return\nclass")


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_python_multi_import_metadata():
    """Intel: detect multiple Python imports"""
    parser = get_parser("python")
    tree = parser.parse(b"import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n")


@pytest.mark.skipif(not has_language("rust"), reason="Language 'rust' not available")
def test_rust_chunking_metadata():
    """Intel: chunk multi-function Rust source into pieces"""
    parser = get_parser("rust")
    tree = parser.parse(b"fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n")


@pytest.mark.skipif(not has_language("rust"), reason="Language 'rust' not available")
def test_rust_function_metadata():
    """Intel: extract structure from Rust function definition"""
    parser = get_parser("rust")
    tree = parser.parse(b"fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


@pytest.mark.skipif(not has_language("typescript"), reason="Language 'typescript' not available")
def test_typescript_function_metadata():
    """Intel: extract structure from TypeScript function"""
    parser = get_parser("typescript")
    tree = parser.parse(b"import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n")
