# Code generated by e2e-generator. DO NOT EDIT.

import pytest
from tree_sitter_language_pack import (
    get_parser,
    has_language,
)

from .helpers import tree_contains_node_type


@pytest.mark.skipif(not has_language("javascript"), reason="Language 'javascript' not available")
def test_parsing_javascript_class():
    """Parse a JavaScript class declaration."""
    parser = get_parser("javascript")
    tree = parser.parse(b"class Foo { bar() {} }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"
    assert tree_contains_node_type(root, "class_declaration"), "Tree should contain a 'class_declaration' node"


@pytest.mark.skipif(not has_language("python"), reason="Language 'python' not available")
def test_parsing_python_function():
    """Parse a Python function definition."""
    parser = get_parser("python")
    tree = parser.parse(b"def hello():\n    pass\n")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"
    assert tree_contains_node_type(root, "function_definition"), "Tree should contain a 'function_definition' node"


@pytest.mark.skipif(not has_language("rust"), reason="Language 'rust' not available")
def test_parsing_rust_struct():
    """Parse a Rust struct definition."""
    parser = get_parser("rust")
    tree = parser.parse(b"struct Point { x: f64, y: f64 }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"
