// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class ParsingTests
{

    [Fact]
    public void ParsingJavascriptClass()
    {
        // Parse a JavaScript class declaration.
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var langPtr = TsPackClient.GetLanguage("javascript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void ParsingPythonFunction()
    {
        // Parse a Python function definition.
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void ParsingRustStruct()
    {
        // Parse a Rust struct definition.
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var langPtr = TsPackClient.GetLanguage("rust");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }
}
