// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class RegistryTests
{

    [Fact]
    public void RegistryHasLanguageFalse()
    {
        // has_language('nonexistent') should return false.
        Assert.False(TsPackClient.HasLanguage("nonexistent"));
    }

    [Fact]
    public void RegistryHasLanguageTrue()
    {
        // has_language('python') should return true.
        Assert.True(TsPackClient.HasLanguage("python"));
    }

    [Fact]
    public void RegistryListLanguages()
    {
        // available_languages should return a non-empty list.
        var langs = TsPackClient.AvailableLanguages();
        Assert.NotEmpty(langs);
    }
}
