// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class SmokeTests
{

    [Fact]
    public void SmokeActionscript()
    {
        // Smoke test: load actionscript and parse a simple snippet
        if (!TsPackClient.HasLanguage("actionscript"))
        {
            return; // Language 'actionscript' not available
        }
        var langPtr = TsPackClient.GetLanguage("actionscript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeAda()
    {
        // Smoke test: load ada and parse a simple snippet
        if (!TsPackClient.HasLanguage("ada"))
        {
            return; // Language 'ada' not available
        }
        var langPtr = TsPackClient.GetLanguage("ada");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeAgda()
    {
        // Smoke test: load agda and parse a simple snippet
        if (!TsPackClient.HasLanguage("agda"))
        {
            return; // Language 'agda' not available
        }
        var langPtr = TsPackClient.GetLanguage("agda");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeApex()
    {
        // Smoke test: load apex and parse a simple snippet
        if (!TsPackClient.HasLanguage("apex"))
        {
            return; // Language 'apex' not available
        }
        var langPtr = TsPackClient.GetLanguage("apex");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeArduino()
    {
        // Smoke test: load arduino and parse a simple snippet
        if (!TsPackClient.HasLanguage("arduino"))
        {
            return; // Language 'arduino' not available
        }
        var langPtr = TsPackClient.GetLanguage("arduino");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeAsm()
    {
        // Smoke test: load asm and parse a simple snippet
        if (!TsPackClient.HasLanguage("asm"))
        {
            return; // Language 'asm' not available
        }
        var langPtr = TsPackClient.GetLanguage("asm");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeAstro()
    {
        // Smoke test: load astro and parse a simple snippet
        if (!TsPackClient.HasLanguage("astro"))
        {
            return; // Language 'astro' not available
        }
        var langPtr = TsPackClient.GetLanguage("astro");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBash()
    {
        // Smoke test: load bash and parse a simple snippet
        if (!TsPackClient.HasLanguage("bash"))
        {
            return; // Language 'bash' not available
        }
        var langPtr = TsPackClient.GetLanguage("bash");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBeancount()
    {
        // Smoke test: load beancount and parse a simple snippet
        if (!TsPackClient.HasLanguage("beancount"))
        {
            return; // Language 'beancount' not available
        }
        var langPtr = TsPackClient.GetLanguage("beancount");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBibtex()
    {
        // Smoke test: load bibtex and parse a simple snippet
        if (!TsPackClient.HasLanguage("bibtex"))
        {
            return; // Language 'bibtex' not available
        }
        var langPtr = TsPackClient.GetLanguage("bibtex");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBicep()
    {
        // Smoke test: load bicep and parse a simple snippet
        if (!TsPackClient.HasLanguage("bicep"))
        {
            return; // Language 'bicep' not available
        }
        var langPtr = TsPackClient.GetLanguage("bicep");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBitbake()
    {
        // Smoke test: load bitbake and parse a simple snippet
        if (!TsPackClient.HasLanguage("bitbake"))
        {
            return; // Language 'bitbake' not available
        }
        var langPtr = TsPackClient.GetLanguage("bitbake");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeBsl()
    {
        // Smoke test: load bsl and parse a simple snippet
        if (!TsPackClient.HasLanguage("bsl"))
        {
            return; // Language 'bsl' not available
        }
        var langPtr = TsPackClient.GetLanguage("bsl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeC()
    {
        // Smoke test: load c and parse a simple snippet
        if (!TsPackClient.HasLanguage("c"))
        {
            return; // Language 'c' not available
        }
        var langPtr = TsPackClient.GetLanguage("c");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCairo()
    {
        // Smoke test: load cairo and parse a simple snippet
        if (!TsPackClient.HasLanguage("cairo"))
        {
            return; // Language 'cairo' not available
        }
        var langPtr = TsPackClient.GetLanguage("cairo");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCapnp()
    {
        // Smoke test: load capnp and parse a simple snippet
        if (!TsPackClient.HasLanguage("capnp"))
        {
            return; // Language 'capnp' not available
        }
        var langPtr = TsPackClient.GetLanguage("capnp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeChatito()
    {
        // Smoke test: load chatito and parse a simple snippet
        if (!TsPackClient.HasLanguage("chatito"))
        {
            return; // Language 'chatito' not available
        }
        var langPtr = TsPackClient.GetLanguage("chatito");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeClarity()
    {
        // Smoke test: load clarity and parse a simple snippet
        if (!TsPackClient.HasLanguage("clarity"))
        {
            return; // Language 'clarity' not available
        }
        var langPtr = TsPackClient.GetLanguage("clarity");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeClojure()
    {
        // Smoke test: load clojure and parse a simple snippet
        if (!TsPackClient.HasLanguage("clojure"))
        {
            return; // Language 'clojure' not available
        }
        var langPtr = TsPackClient.GetLanguage("clojure");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCmake()
    {
        // Smoke test: load cmake and parse a simple snippet
        if (!TsPackClient.HasLanguage("cmake"))
        {
            return; // Language 'cmake' not available
        }
        var langPtr = TsPackClient.GetLanguage("cmake");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCobol()
    {
        // Smoke test: load cobol and parse a simple snippet
        if (!TsPackClient.HasLanguage("cobol"))
        {
            return; // Language 'cobol' not available
        }
        var langPtr = TsPackClient.GetLanguage("cobol");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeComment()
    {
        // Smoke test: load comment and parse a simple snippet
        if (!TsPackClient.HasLanguage("comment"))
        {
            return; // Language 'comment' not available
        }
        var langPtr = TsPackClient.GetLanguage("comment");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCommonlisp()
    {
        // Smoke test: load commonlisp and parse a simple snippet
        if (!TsPackClient.HasLanguage("commonlisp"))
        {
            return; // Language 'commonlisp' not available
        }
        var langPtr = TsPackClient.GetLanguage("commonlisp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCpon()
    {
        // Smoke test: load cpon and parse a simple snippet
        if (!TsPackClient.HasLanguage("cpon"))
        {
            return; // Language 'cpon' not available
        }
        var langPtr = TsPackClient.GetLanguage("cpon");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCpp()
    {
        // Smoke test: load cpp and parse a simple snippet
        if (!TsPackClient.HasLanguage("cpp"))
        {
            return; // Language 'cpp' not available
        }
        var langPtr = TsPackClient.GetLanguage("cpp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCsharp()
    {
        // Smoke test: load csharp and parse a simple snippet
        if (!TsPackClient.HasLanguage("csharp"))
        {
            return; // Language 'csharp' not available
        }
        var langPtr = TsPackClient.GetLanguage("csharp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCss()
    {
        // Smoke test: load css and parse a simple snippet
        if (!TsPackClient.HasLanguage("css"))
        {
            return; // Language 'css' not available
        }
        var langPtr = TsPackClient.GetLanguage("css");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCsv()
    {
        // Smoke test: load csv and parse a simple snippet
        if (!TsPackClient.HasLanguage("csv"))
        {
            return; // Language 'csv' not available
        }
        var langPtr = TsPackClient.GetLanguage("csv");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeCuda()
    {
        // Smoke test: load cuda and parse a simple snippet
        if (!TsPackClient.HasLanguage("cuda"))
        {
            return; // Language 'cuda' not available
        }
        var langPtr = TsPackClient.GetLanguage("cuda");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeD()
    {
        // Smoke test: load d and parse a simple snippet
        if (!TsPackClient.HasLanguage("d"))
        {
            return; // Language 'd' not available
        }
        var langPtr = TsPackClient.GetLanguage("d");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeDart()
    {
        // Smoke test: load dart and parse a simple snippet
        if (!TsPackClient.HasLanguage("dart"))
        {
            return; // Language 'dart' not available
        }
        var langPtr = TsPackClient.GetLanguage("dart");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeDockerfile()
    {
        // Smoke test: load dockerfile and parse a simple snippet
        if (!TsPackClient.HasLanguage("dockerfile"))
        {
            return; // Language 'dockerfile' not available
        }
        var langPtr = TsPackClient.GetLanguage("dockerfile");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeDoxygen()
    {
        // Smoke test: load doxygen and parse a simple snippet
        if (!TsPackClient.HasLanguage("doxygen"))
        {
            return; // Language 'doxygen' not available
        }
        var langPtr = TsPackClient.GetLanguage("doxygen");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeDtd()
    {
        // Smoke test: load dtd and parse a simple snippet
        if (!TsPackClient.HasLanguage("dtd"))
        {
            return; // Language 'dtd' not available
        }
        var langPtr = TsPackClient.GetLanguage("dtd");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeElisp()
    {
        // Smoke test: load elisp and parse a simple snippet
        if (!TsPackClient.HasLanguage("elisp"))
        {
            return; // Language 'elisp' not available
        }
        var langPtr = TsPackClient.GetLanguage("elisp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeElixir()
    {
        // Smoke test: load elixir and parse a simple snippet
        if (!TsPackClient.HasLanguage("elixir"))
        {
            return; // Language 'elixir' not available
        }
        var langPtr = TsPackClient.GetLanguage("elixir");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeElm()
    {
        // Smoke test: load elm and parse a simple snippet
        if (!TsPackClient.HasLanguage("elm"))
        {
            return; // Language 'elm' not available
        }
        var langPtr = TsPackClient.GetLanguage("elm");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeEmbeddedtemplate()
    {
        // Smoke test: load embeddedtemplate and parse a simple snippet
        if (!TsPackClient.HasLanguage("embeddedtemplate"))
        {
            return; // Language 'embeddedtemplate' not available
        }
        var langPtr = TsPackClient.GetLanguage("embeddedtemplate");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeErlang()
    {
        // Smoke test: load erlang and parse a simple snippet
        if (!TsPackClient.HasLanguage("erlang"))
        {
            return; // Language 'erlang' not available
        }
        var langPtr = TsPackClient.GetLanguage("erlang");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFennel()
    {
        // Smoke test: load fennel and parse a simple snippet
        if (!TsPackClient.HasLanguage("fennel"))
        {
            return; // Language 'fennel' not available
        }
        var langPtr = TsPackClient.GetLanguage("fennel");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFirrtl()
    {
        // Smoke test: load firrtl and parse a simple snippet
        if (!TsPackClient.HasLanguage("firrtl"))
        {
            return; // Language 'firrtl' not available
        }
        var langPtr = TsPackClient.GetLanguage("firrtl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFish()
    {
        // Smoke test: load fish and parse a simple snippet
        if (!TsPackClient.HasLanguage("fish"))
        {
            return; // Language 'fish' not available
        }
        var langPtr = TsPackClient.GetLanguage("fish");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFortran()
    {
        // Smoke test: load fortran and parse a simple snippet
        if (!TsPackClient.HasLanguage("fortran"))
        {
            return; // Language 'fortran' not available
        }
        var langPtr = TsPackClient.GetLanguage("fortran");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFsharp()
    {
        // Smoke test: load fsharp and parse a simple snippet
        if (!TsPackClient.HasLanguage("fsharp"))
        {
            return; // Language 'fsharp' not available
        }
        var langPtr = TsPackClient.GetLanguage("fsharp");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFsharpSignature()
    {
        // Smoke test: load fsharp_signature and parse a simple snippet
        if (!TsPackClient.HasLanguage("fsharp_signature"))
        {
            return; // Language 'fsharp_signature' not available
        }
        var langPtr = TsPackClient.GetLanguage("fsharp_signature");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeFunc()
    {
        // Smoke test: load func and parse a simple snippet
        if (!TsPackClient.HasLanguage("func"))
        {
            return; // Language 'func' not available
        }
        var langPtr = TsPackClient.GetLanguage("func");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGdscript()
    {
        // Smoke test: load gdscript and parse a simple snippet
        if (!TsPackClient.HasLanguage("gdscript"))
        {
            return; // Language 'gdscript' not available
        }
        var langPtr = TsPackClient.GetLanguage("gdscript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGitattributes()
    {
        // Smoke test: load gitattributes and parse a simple snippet
        if (!TsPackClient.HasLanguage("gitattributes"))
        {
            return; // Language 'gitattributes' not available
        }
        var langPtr = TsPackClient.GetLanguage("gitattributes");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGitcommit()
    {
        // Smoke test: load gitcommit and parse a simple snippet
        if (!TsPackClient.HasLanguage("gitcommit"))
        {
            return; // Language 'gitcommit' not available
        }
        var langPtr = TsPackClient.GetLanguage("gitcommit");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGitignore()
    {
        // Smoke test: load gitignore and parse a simple snippet
        if (!TsPackClient.HasLanguage("gitignore"))
        {
            return; // Language 'gitignore' not available
        }
        var langPtr = TsPackClient.GetLanguage("gitignore");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGleam()
    {
        // Smoke test: load gleam and parse a simple snippet
        if (!TsPackClient.HasLanguage("gleam"))
        {
            return; // Language 'gleam' not available
        }
        var langPtr = TsPackClient.GetLanguage("gleam");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGlsl()
    {
        // Smoke test: load glsl and parse a simple snippet
        if (!TsPackClient.HasLanguage("glsl"))
        {
            return; // Language 'glsl' not available
        }
        var langPtr = TsPackClient.GetLanguage("glsl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGn()
    {
        // Smoke test: load gn and parse a simple snippet
        if (!TsPackClient.HasLanguage("gn"))
        {
            return; // Language 'gn' not available
        }
        var langPtr = TsPackClient.GetLanguage("gn");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGo()
    {
        // Smoke test: load go and parse a simple snippet
        if (!TsPackClient.HasLanguage("go"))
        {
            return; // Language 'go' not available
        }
        var langPtr = TsPackClient.GetLanguage("go");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGomod()
    {
        // Smoke test: load gomod and parse a simple snippet
        if (!TsPackClient.HasLanguage("gomod"))
        {
            return; // Language 'gomod' not available
        }
        var langPtr = TsPackClient.GetLanguage("gomod");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGosum()
    {
        // Smoke test: load gosum and parse a simple snippet
        if (!TsPackClient.HasLanguage("gosum"))
        {
            return; // Language 'gosum' not available
        }
        var langPtr = TsPackClient.GetLanguage("gosum");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGraphql()
    {
        // Smoke test: load graphql and parse a simple snippet
        if (!TsPackClient.HasLanguage("graphql"))
        {
            return; // Language 'graphql' not available
        }
        var langPtr = TsPackClient.GetLanguage("graphql");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGroovy()
    {
        // Smoke test: load groovy and parse a simple snippet
        if (!TsPackClient.HasLanguage("groovy"))
        {
            return; // Language 'groovy' not available
        }
        var langPtr = TsPackClient.GetLanguage("groovy");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeGstlaunch()
    {
        // Smoke test: load gstlaunch and parse a simple snippet
        if (!TsPackClient.HasLanguage("gstlaunch"))
        {
            return; // Language 'gstlaunch' not available
        }
        var langPtr = TsPackClient.GetLanguage("gstlaunch");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHack()
    {
        // Smoke test: load hack and parse a simple snippet
        if (!TsPackClient.HasLanguage("hack"))
        {
            return; // Language 'hack' not available
        }
        var langPtr = TsPackClient.GetLanguage("hack");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHare()
    {
        // Smoke test: load hare and parse a simple snippet
        if (!TsPackClient.HasLanguage("hare"))
        {
            return; // Language 'hare' not available
        }
        var langPtr = TsPackClient.GetLanguage("hare");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHaskell()
    {
        // Smoke test: load haskell and parse a simple snippet
        if (!TsPackClient.HasLanguage("haskell"))
        {
            return; // Language 'haskell' not available
        }
        var langPtr = TsPackClient.GetLanguage("haskell");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHaxe()
    {
        // Smoke test: load haxe and parse a simple snippet
        if (!TsPackClient.HasLanguage("haxe"))
        {
            return; // Language 'haxe' not available
        }
        var langPtr = TsPackClient.GetLanguage("haxe");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHcl()
    {
        // Smoke test: load hcl and parse a simple snippet
        if (!TsPackClient.HasLanguage("hcl"))
        {
            return; // Language 'hcl' not available
        }
        var langPtr = TsPackClient.GetLanguage("hcl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHeex()
    {
        // Smoke test: load heex and parse a simple snippet
        if (!TsPackClient.HasLanguage("heex"))
        {
            return; // Language 'heex' not available
        }
        var langPtr = TsPackClient.GetLanguage("heex");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHlsl()
    {
        // Smoke test: load hlsl and parse a simple snippet
        if (!TsPackClient.HasLanguage("hlsl"))
        {
            return; // Language 'hlsl' not available
        }
        var langPtr = TsPackClient.GetLanguage("hlsl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHtml()
    {
        // Smoke test: load html and parse a simple snippet
        if (!TsPackClient.HasLanguage("html"))
        {
            return; // Language 'html' not available
        }
        var langPtr = TsPackClient.GetLanguage("html");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeHyprlang()
    {
        // Smoke test: load hyprlang and parse a simple snippet
        if (!TsPackClient.HasLanguage("hyprlang"))
        {
            return; // Language 'hyprlang' not available
        }
        var langPtr = TsPackClient.GetLanguage("hyprlang");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeIni()
    {
        // Smoke test: load ini and parse a simple snippet
        if (!TsPackClient.HasLanguage("ini"))
        {
            return; // Language 'ini' not available
        }
        var langPtr = TsPackClient.GetLanguage("ini");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeIspc()
    {
        // Smoke test: load ispc and parse a simple snippet
        if (!TsPackClient.HasLanguage("ispc"))
        {
            return; // Language 'ispc' not available
        }
        var langPtr = TsPackClient.GetLanguage("ispc");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJanet()
    {
        // Smoke test: load janet and parse a simple snippet
        if (!TsPackClient.HasLanguage("janet"))
        {
            return; // Language 'janet' not available
        }
        var langPtr = TsPackClient.GetLanguage("janet");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJava()
    {
        // Smoke test: load java and parse a simple snippet
        if (!TsPackClient.HasLanguage("java"))
        {
            return; // Language 'java' not available
        }
        var langPtr = TsPackClient.GetLanguage("java");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJavascript()
    {
        // Smoke test: load javascript and parse a simple snippet
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var langPtr = TsPackClient.GetLanguage("javascript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJsdoc()
    {
        // Smoke test: load jsdoc and parse a simple snippet
        if (!TsPackClient.HasLanguage("jsdoc"))
        {
            return; // Language 'jsdoc' not available
        }
        var langPtr = TsPackClient.GetLanguage("jsdoc");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJson()
    {
        // Smoke test: load json and parse a simple snippet
        if (!TsPackClient.HasLanguage("json"))
        {
            return; // Language 'json' not available
        }
        var langPtr = TsPackClient.GetLanguage("json");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJsonnet()
    {
        // Smoke test: load jsonnet and parse a simple snippet
        if (!TsPackClient.HasLanguage("jsonnet"))
        {
            return; // Language 'jsonnet' not available
        }
        var langPtr = TsPackClient.GetLanguage("jsonnet");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeJulia()
    {
        // Smoke test: load julia and parse a simple snippet
        if (!TsPackClient.HasLanguage("julia"))
        {
            return; // Language 'julia' not available
        }
        var langPtr = TsPackClient.GetLanguage("julia");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeKconfig()
    {
        // Smoke test: load kconfig and parse a simple snippet
        if (!TsPackClient.HasLanguage("kconfig"))
        {
            return; // Language 'kconfig' not available
        }
        var langPtr = TsPackClient.GetLanguage("kconfig");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeKdl()
    {
        // Smoke test: load kdl and parse a simple snippet
        if (!TsPackClient.HasLanguage("kdl"))
        {
            return; // Language 'kdl' not available
        }
        var langPtr = TsPackClient.GetLanguage("kdl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeKotlin()
    {
        // Smoke test: load kotlin and parse a simple snippet
        if (!TsPackClient.HasLanguage("kotlin"))
        {
            return; // Language 'kotlin' not available
        }
        var langPtr = TsPackClient.GetLanguage("kotlin");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLatex()
    {
        // Smoke test: load latex and parse a simple snippet
        if (!TsPackClient.HasLanguage("latex"))
        {
            return; // Language 'latex' not available
        }
        var langPtr = TsPackClient.GetLanguage("latex");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLinkerscript()
    {
        // Smoke test: load linkerscript and parse a simple snippet
        if (!TsPackClient.HasLanguage("linkerscript"))
        {
            return; // Language 'linkerscript' not available
        }
        var langPtr = TsPackClient.GetLanguage("linkerscript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLlvm()
    {
        // Smoke test: load llvm and parse a simple snippet
        if (!TsPackClient.HasLanguage("llvm"))
        {
            return; // Language 'llvm' not available
        }
        var langPtr = TsPackClient.GetLanguage("llvm");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLua()
    {
        // Smoke test: load lua and parse a simple snippet
        if (!TsPackClient.HasLanguage("lua"))
        {
            return; // Language 'lua' not available
        }
        var langPtr = TsPackClient.GetLanguage("lua");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLuadoc()
    {
        // Smoke test: load luadoc and parse a simple snippet
        if (!TsPackClient.HasLanguage("luadoc"))
        {
            return; // Language 'luadoc' not available
        }
        var langPtr = TsPackClient.GetLanguage("luadoc");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLuap()
    {
        // Smoke test: load luap and parse a simple snippet
        if (!TsPackClient.HasLanguage("luap"))
        {
            return; // Language 'luap' not available
        }
        var langPtr = TsPackClient.GetLanguage("luap");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeLuau()
    {
        // Smoke test: load luau and parse a simple snippet
        if (!TsPackClient.HasLanguage("luau"))
        {
            return; // Language 'luau' not available
        }
        var langPtr = TsPackClient.GetLanguage("luau");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMagik()
    {
        // Smoke test: load magik and parse a simple snippet
        if (!TsPackClient.HasLanguage("magik"))
        {
            return; // Language 'magik' not available
        }
        var langPtr = TsPackClient.GetLanguage("magik");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMake()
    {
        // Smoke test: load make and parse a simple snippet
        if (!TsPackClient.HasLanguage("make"))
        {
            return; // Language 'make' not available
        }
        var langPtr = TsPackClient.GetLanguage("make");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMarkdown()
    {
        // Smoke test: load markdown and parse a simple snippet
        if (!TsPackClient.HasLanguage("markdown"))
        {
            return; // Language 'markdown' not available
        }
        var langPtr = TsPackClient.GetLanguage("markdown");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMarkdownInline()
    {
        // Smoke test: load markdown_inline and parse a simple snippet
        if (!TsPackClient.HasLanguage("markdown_inline"))
        {
            return; // Language 'markdown_inline' not available
        }
        var langPtr = TsPackClient.GetLanguage("markdown_inline");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMatlab()
    {
        // Smoke test: load matlab and parse a simple snippet
        if (!TsPackClient.HasLanguage("matlab"))
        {
            return; // Language 'matlab' not available
        }
        var langPtr = TsPackClient.GetLanguage("matlab");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMermaid()
    {
        // Smoke test: load mermaid and parse a simple snippet
        if (!TsPackClient.HasLanguage("mermaid"))
        {
            return; // Language 'mermaid' not available
        }
        var langPtr = TsPackClient.GetLanguage("mermaid");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeMeson()
    {
        // Smoke test: load meson and parse a simple snippet
        if (!TsPackClient.HasLanguage("meson"))
        {
            return; // Language 'meson' not available
        }
        var langPtr = TsPackClient.GetLanguage("meson");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeNetlinx()
    {
        // Smoke test: load netlinx and parse a simple snippet
        if (!TsPackClient.HasLanguage("netlinx"))
        {
            return; // Language 'netlinx' not available
        }
        var langPtr = TsPackClient.GetLanguage("netlinx");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeNim()
    {
        // Smoke test: load nim and parse a simple snippet
        if (!TsPackClient.HasLanguage("nim"))
        {
            return; // Language 'nim' not available
        }
        var langPtr = TsPackClient.GetLanguage("nim");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeNinja()
    {
        // Smoke test: load ninja and parse a simple snippet
        if (!TsPackClient.HasLanguage("ninja"))
        {
            return; // Language 'ninja' not available
        }
        var langPtr = TsPackClient.GetLanguage("ninja");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeNix()
    {
        // Smoke test: load nix and parse a simple snippet
        if (!TsPackClient.HasLanguage("nix"))
        {
            return; // Language 'nix' not available
        }
        var langPtr = TsPackClient.GetLanguage("nix");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeNqc()
    {
        // Smoke test: load nqc and parse a simple snippet
        if (!TsPackClient.HasLanguage("nqc"))
        {
            return; // Language 'nqc' not available
        }
        var langPtr = TsPackClient.GetLanguage("nqc");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeObjc()
    {
        // Smoke test: load objc and parse a simple snippet
        if (!TsPackClient.HasLanguage("objc"))
        {
            return; // Language 'objc' not available
        }
        var langPtr = TsPackClient.GetLanguage("objc");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeOcaml()
    {
        // Smoke test: load ocaml and parse a simple snippet
        if (!TsPackClient.HasLanguage("ocaml"))
        {
            return; // Language 'ocaml' not available
        }
        var langPtr = TsPackClient.GetLanguage("ocaml");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeOcamlInterface()
    {
        // Smoke test: load ocaml_interface and parse a simple snippet
        if (!TsPackClient.HasLanguage("ocaml_interface"))
        {
            return; // Language 'ocaml_interface' not available
        }
        var langPtr = TsPackClient.GetLanguage("ocaml_interface");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeOdin()
    {
        // Smoke test: load odin and parse a simple snippet
        if (!TsPackClient.HasLanguage("odin"))
        {
            return; // Language 'odin' not available
        }
        var langPtr = TsPackClient.GetLanguage("odin");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeOrg()
    {
        // Smoke test: load org and parse a simple snippet
        if (!TsPackClient.HasLanguage("org"))
        {
            return; // Language 'org' not available
        }
        var langPtr = TsPackClient.GetLanguage("org");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePascal()
    {
        // Smoke test: load pascal and parse a simple snippet
        if (!TsPackClient.HasLanguage("pascal"))
        {
            return; // Language 'pascal' not available
        }
        var langPtr = TsPackClient.GetLanguage("pascal");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePem()
    {
        // Smoke test: load pem and parse a simple snippet
        if (!TsPackClient.HasLanguage("pem"))
        {
            return; // Language 'pem' not available
        }
        var langPtr = TsPackClient.GetLanguage("pem");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePerl()
    {
        // Smoke test: load perl and parse a simple snippet
        if (!TsPackClient.HasLanguage("perl"))
        {
            return; // Language 'perl' not available
        }
        var langPtr = TsPackClient.GetLanguage("perl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePgn()
    {
        // Smoke test: load pgn and parse a simple snippet
        if (!TsPackClient.HasLanguage("pgn"))
        {
            return; // Language 'pgn' not available
        }
        var langPtr = TsPackClient.GetLanguage("pgn");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePhp()
    {
        // Smoke test: load php and parse a simple snippet
        if (!TsPackClient.HasLanguage("php"))
        {
            return; // Language 'php' not available
        }
        var langPtr = TsPackClient.GetLanguage("php");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePo()
    {
        // Smoke test: load po and parse a simple snippet
        if (!TsPackClient.HasLanguage("po"))
        {
            return; // Language 'po' not available
        }
        var langPtr = TsPackClient.GetLanguage("po");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePony()
    {
        // Smoke test: load pony and parse a simple snippet
        if (!TsPackClient.HasLanguage("pony"))
        {
            return; // Language 'pony' not available
        }
        var langPtr = TsPackClient.GetLanguage("pony");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePowershell()
    {
        // Smoke test: load powershell and parse a simple snippet
        if (!TsPackClient.HasLanguage("powershell"))
        {
            return; // Language 'powershell' not available
        }
        var langPtr = TsPackClient.GetLanguage("powershell");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePrintf()
    {
        // Smoke test: load printf and parse a simple snippet
        if (!TsPackClient.HasLanguage("printf"))
        {
            return; // Language 'printf' not available
        }
        var langPtr = TsPackClient.GetLanguage("printf");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePrisma()
    {
        // Smoke test: load prisma and parse a simple snippet
        if (!TsPackClient.HasLanguage("prisma"))
        {
            return; // Language 'prisma' not available
        }
        var langPtr = TsPackClient.GetLanguage("prisma");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeProperties()
    {
        // Smoke test: load properties and parse a simple snippet
        if (!TsPackClient.HasLanguage("properties"))
        {
            return; // Language 'properties' not available
        }
        var langPtr = TsPackClient.GetLanguage("properties");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeProto()
    {
        // Smoke test: load proto and parse a simple snippet
        if (!TsPackClient.HasLanguage("proto"))
        {
            return; // Language 'proto' not available
        }
        var langPtr = TsPackClient.GetLanguage("proto");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePsv()
    {
        // Smoke test: load psv and parse a simple snippet
        if (!TsPackClient.HasLanguage("psv"))
        {
            return; // Language 'psv' not available
        }
        var langPtr = TsPackClient.GetLanguage("psv");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePuppet()
    {
        // Smoke test: load puppet and parse a simple snippet
        if (!TsPackClient.HasLanguage("puppet"))
        {
            return; // Language 'puppet' not available
        }
        var langPtr = TsPackClient.GetLanguage("puppet");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePurescript()
    {
        // Smoke test: load purescript and parse a simple snippet
        if (!TsPackClient.HasLanguage("purescript"))
        {
            return; // Language 'purescript' not available
        }
        var langPtr = TsPackClient.GetLanguage("purescript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePymanifest()
    {
        // Smoke test: load pymanifest and parse a simple snippet
        if (!TsPackClient.HasLanguage("pymanifest"))
        {
            return; // Language 'pymanifest' not available
        }
        var langPtr = TsPackClient.GetLanguage("pymanifest");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokePython()
    {
        // Smoke test: load python and parse a simple snippet
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeQmldir()
    {
        // Smoke test: load qmldir and parse a simple snippet
        if (!TsPackClient.HasLanguage("qmldir"))
        {
            return; // Language 'qmldir' not available
        }
        var langPtr = TsPackClient.GetLanguage("qmldir");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeQmljs()
    {
        // Smoke test: load qmljs and parse a simple snippet
        if (!TsPackClient.HasLanguage("qmljs"))
        {
            return; // Language 'qmljs' not available
        }
        var langPtr = TsPackClient.GetLanguage("qmljs");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeQuery()
    {
        // Smoke test: load query and parse a simple snippet
        if (!TsPackClient.HasLanguage("query"))
        {
            return; // Language 'query' not available
        }
        var langPtr = TsPackClient.GetLanguage("query");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeR()
    {
        // Smoke test: load r and parse a simple snippet
        if (!TsPackClient.HasLanguage("r"))
        {
            return; // Language 'r' not available
        }
        var langPtr = TsPackClient.GetLanguage("r");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRacket()
    {
        // Smoke test: load racket and parse a simple snippet
        if (!TsPackClient.HasLanguage("racket"))
        {
            return; // Language 'racket' not available
        }
        var langPtr = TsPackClient.GetLanguage("racket");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRe2c()
    {
        // Smoke test: load re2c and parse a simple snippet
        if (!TsPackClient.HasLanguage("re2c"))
        {
            return; // Language 're2c' not available
        }
        var langPtr = TsPackClient.GetLanguage("re2c");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeReadline()
    {
        // Smoke test: load readline and parse a simple snippet
        if (!TsPackClient.HasLanguage("readline"))
        {
            return; // Language 'readline' not available
        }
        var langPtr = TsPackClient.GetLanguage("readline");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRegex()
    {
        // Smoke test: load regex and parse a simple snippet
        if (!TsPackClient.HasLanguage("regex"))
        {
            return; // Language 'regex' not available
        }
        var langPtr = TsPackClient.GetLanguage("regex");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRego()
    {
        // Smoke test: load rego and parse a simple snippet
        if (!TsPackClient.HasLanguage("rego"))
        {
            return; // Language 'rego' not available
        }
        var langPtr = TsPackClient.GetLanguage("rego");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRequirements()
    {
        // Smoke test: load requirements and parse a simple snippet
        if (!TsPackClient.HasLanguage("requirements"))
        {
            return; // Language 'requirements' not available
        }
        var langPtr = TsPackClient.GetLanguage("requirements");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRon()
    {
        // Smoke test: load ron and parse a simple snippet
        if (!TsPackClient.HasLanguage("ron"))
        {
            return; // Language 'ron' not available
        }
        var langPtr = TsPackClient.GetLanguage("ron");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRst()
    {
        // Smoke test: load rst and parse a simple snippet
        if (!TsPackClient.HasLanguage("rst"))
        {
            return; // Language 'rst' not available
        }
        var langPtr = TsPackClient.GetLanguage("rst");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRuby()
    {
        // Smoke test: load ruby and parse a simple snippet
        if (!TsPackClient.HasLanguage("ruby"))
        {
            return; // Language 'ruby' not available
        }
        var langPtr = TsPackClient.GetLanguage("ruby");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeRust()
    {
        // Smoke test: load rust and parse a simple snippet
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var langPtr = TsPackClient.GetLanguage("rust");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeScala()
    {
        // Smoke test: load scala and parse a simple snippet
        if (!TsPackClient.HasLanguage("scala"))
        {
            return; // Language 'scala' not available
        }
        var langPtr = TsPackClient.GetLanguage("scala");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeScheme()
    {
        // Smoke test: load scheme and parse a simple snippet
        if (!TsPackClient.HasLanguage("scheme"))
        {
            return; // Language 'scheme' not available
        }
        var langPtr = TsPackClient.GetLanguage("scheme");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeScss()
    {
        // Smoke test: load scss and parse a simple snippet
        if (!TsPackClient.HasLanguage("scss"))
        {
            return; // Language 'scss' not available
        }
        var langPtr = TsPackClient.GetLanguage("scss");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSmali()
    {
        // Smoke test: load smali and parse a simple snippet
        if (!TsPackClient.HasLanguage("smali"))
        {
            return; // Language 'smali' not available
        }
        var langPtr = TsPackClient.GetLanguage("smali");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSmithy()
    {
        // Smoke test: load smithy and parse a simple snippet
        if (!TsPackClient.HasLanguage("smithy"))
        {
            return; // Language 'smithy' not available
        }
        var langPtr = TsPackClient.GetLanguage("smithy");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSolidity()
    {
        // Smoke test: load solidity and parse a simple snippet
        if (!TsPackClient.HasLanguage("solidity"))
        {
            return; // Language 'solidity' not available
        }
        var langPtr = TsPackClient.GetLanguage("solidity");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSparql()
    {
        // Smoke test: load sparql and parse a simple snippet
        if (!TsPackClient.HasLanguage("sparql"))
        {
            return; // Language 'sparql' not available
        }
        var langPtr = TsPackClient.GetLanguage("sparql");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSql()
    {
        // Smoke test: load sql and parse a simple snippet
        if (!TsPackClient.HasLanguage("sql"))
        {
            return; // Language 'sql' not available
        }
        var langPtr = TsPackClient.GetLanguage("sql");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSquirrel()
    {
        // Smoke test: load squirrel and parse a simple snippet
        if (!TsPackClient.HasLanguage("squirrel"))
        {
            return; // Language 'squirrel' not available
        }
        var langPtr = TsPackClient.GetLanguage("squirrel");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeStarlark()
    {
        // Smoke test: load starlark and parse a simple snippet
        if (!TsPackClient.HasLanguage("starlark"))
        {
            return; // Language 'starlark' not available
        }
        var langPtr = TsPackClient.GetLanguage("starlark");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSvelte()
    {
        // Smoke test: load svelte and parse a simple snippet
        if (!TsPackClient.HasLanguage("svelte"))
        {
            return; // Language 'svelte' not available
        }
        var langPtr = TsPackClient.GetLanguage("svelte");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeSwift()
    {
        // Smoke test: load swift and parse a simple snippet
        if (!TsPackClient.HasLanguage("swift"))
        {
            return; // Language 'swift' not available
        }
        var langPtr = TsPackClient.GetLanguage("swift");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTablegen()
    {
        // Smoke test: load tablegen and parse a simple snippet
        if (!TsPackClient.HasLanguage("tablegen"))
        {
            return; // Language 'tablegen' not available
        }
        var langPtr = TsPackClient.GetLanguage("tablegen");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTcl()
    {
        // Smoke test: load tcl and parse a simple snippet
        if (!TsPackClient.HasLanguage("tcl"))
        {
            return; // Language 'tcl' not available
        }
        var langPtr = TsPackClient.GetLanguage("tcl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTerraform()
    {
        // Smoke test: load terraform and parse a simple snippet
        if (!TsPackClient.HasLanguage("terraform"))
        {
            return; // Language 'terraform' not available
        }
        var langPtr = TsPackClient.GetLanguage("terraform");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTest()
    {
        // Smoke test: load test and parse a simple snippet
        if (!TsPackClient.HasLanguage("test"))
        {
            return; // Language 'test' not available
        }
        var langPtr = TsPackClient.GetLanguage("test");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeThrift()
    {
        // Smoke test: load thrift and parse a simple snippet
        if (!TsPackClient.HasLanguage("thrift"))
        {
            return; // Language 'thrift' not available
        }
        var langPtr = TsPackClient.GetLanguage("thrift");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeToml()
    {
        // Smoke test: load toml and parse a simple snippet
        if (!TsPackClient.HasLanguage("toml"))
        {
            return; // Language 'toml' not available
        }
        var langPtr = TsPackClient.GetLanguage("toml");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTsv()
    {
        // Smoke test: load tsv and parse a simple snippet
        if (!TsPackClient.HasLanguage("tsv"))
        {
            return; // Language 'tsv' not available
        }
        var langPtr = TsPackClient.GetLanguage("tsv");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTsx()
    {
        // Smoke test: load tsx and parse a simple snippet
        if (!TsPackClient.HasLanguage("tsx"))
        {
            return; // Language 'tsx' not available
        }
        var langPtr = TsPackClient.GetLanguage("tsx");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTwig()
    {
        // Smoke test: load twig and parse a simple snippet
        if (!TsPackClient.HasLanguage("twig"))
        {
            return; // Language 'twig' not available
        }
        var langPtr = TsPackClient.GetLanguage("twig");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTypescript()
    {
        // Smoke test: load typescript and parse a simple snippet
        if (!TsPackClient.HasLanguage("typescript"))
        {
            return; // Language 'typescript' not available
        }
        var langPtr = TsPackClient.GetLanguage("typescript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeTypst()
    {
        // Smoke test: load typst and parse a simple snippet
        if (!TsPackClient.HasLanguage("typst"))
        {
            return; // Language 'typst' not available
        }
        var langPtr = TsPackClient.GetLanguage("typst");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeUdev()
    {
        // Smoke test: load udev and parse a simple snippet
        if (!TsPackClient.HasLanguage("udev"))
        {
            return; // Language 'udev' not available
        }
        var langPtr = TsPackClient.GetLanguage("udev");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeUngrammar()
    {
        // Smoke test: load ungrammar and parse a simple snippet
        if (!TsPackClient.HasLanguage("ungrammar"))
        {
            return; // Language 'ungrammar' not available
        }
        var langPtr = TsPackClient.GetLanguage("ungrammar");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeUxntal()
    {
        // Smoke test: load uxntal and parse a simple snippet
        if (!TsPackClient.HasLanguage("uxntal"))
        {
            return; // Language 'uxntal' not available
        }
        var langPtr = TsPackClient.GetLanguage("uxntal");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeV()
    {
        // Smoke test: load v and parse a simple snippet
        if (!TsPackClient.HasLanguage("v"))
        {
            return; // Language 'v' not available
        }
        var langPtr = TsPackClient.GetLanguage("v");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeVerilog()
    {
        // Smoke test: load verilog and parse a simple snippet
        if (!TsPackClient.HasLanguage("verilog"))
        {
            return; // Language 'verilog' not available
        }
        var langPtr = TsPackClient.GetLanguage("verilog");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeVhdl()
    {
        // Smoke test: load vhdl and parse a simple snippet
        if (!TsPackClient.HasLanguage("vhdl"))
        {
            return; // Language 'vhdl' not available
        }
        var langPtr = TsPackClient.GetLanguage("vhdl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeVim()
    {
        // Smoke test: load vim and parse a simple snippet
        if (!TsPackClient.HasLanguage("vim"))
        {
            return; // Language 'vim' not available
        }
        var langPtr = TsPackClient.GetLanguage("vim");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeVue()
    {
        // Smoke test: load vue and parse a simple snippet
        if (!TsPackClient.HasLanguage("vue"))
        {
            return; // Language 'vue' not available
        }
        var langPtr = TsPackClient.GetLanguage("vue");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeWast()
    {
        // Smoke test: load wast and parse a simple snippet
        if (!TsPackClient.HasLanguage("wast"))
        {
            return; // Language 'wast' not available
        }
        var langPtr = TsPackClient.GetLanguage("wast");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeWat()
    {
        // Smoke test: load wat and parse a simple snippet
        if (!TsPackClient.HasLanguage("wat"))
        {
            return; // Language 'wat' not available
        }
        var langPtr = TsPackClient.GetLanguage("wat");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeWgsl()
    {
        // Smoke test: load wgsl and parse a simple snippet
        if (!TsPackClient.HasLanguage("wgsl"))
        {
            return; // Language 'wgsl' not available
        }
        var langPtr = TsPackClient.GetLanguage("wgsl");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeXcompose()
    {
        // Smoke test: load xcompose and parse a simple snippet
        if (!TsPackClient.HasLanguage("xcompose"))
        {
            return; // Language 'xcompose' not available
        }
        var langPtr = TsPackClient.GetLanguage("xcompose");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeXml()
    {
        // Smoke test: load xml and parse a simple snippet
        if (!TsPackClient.HasLanguage("xml"))
        {
            return; // Language 'xml' not available
        }
        var langPtr = TsPackClient.GetLanguage("xml");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeYaml()
    {
        // Smoke test: load yaml and parse a simple snippet
        if (!TsPackClient.HasLanguage("yaml"))
        {
            return; // Language 'yaml' not available
        }
        var langPtr = TsPackClient.GetLanguage("yaml");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeYuck()
    {
        // Smoke test: load yuck and parse a simple snippet
        if (!TsPackClient.HasLanguage("yuck"))
        {
            return; // Language 'yuck' not available
        }
        var langPtr = TsPackClient.GetLanguage("yuck");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void SmokeZig()
    {
        // Smoke test: load zig and parse a simple snippet
        if (!TsPackClient.HasLanguage("zig"))
        {
            return; // Language 'zig' not available
        }
        var langPtr = TsPackClient.GetLanguage("zig");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }
}
