// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
} from "./helpers";

describe("parsing", () => {
  it("parsing_javascript_class", () => {
    // Parse a JavaScript class declaration.
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", `class Foo { bar() {} }`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    expect(treeContainsNodeType(tree, "class_declaration")).toBe(true);
    freeTree(tree);
  });

});
