// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
} from "./helpers";

describe("registry", () => {
  it("registry_list_languages", () => {
    // available_languages should return a non-empty list.
    const langs = availableLanguages();
    expect(langs.length).toBeGreaterThan(0);
  });

});
