// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
} from "./helpers";

describe("smoke", () => {
  it("smoke_astro", () => {
    // Smoke test: load astro and parse a simple snippet
    if (!hasLanguage("astro")) {
      console.log("Skipping: language 'astro' not available");
      return;
    }
    const tree = parseString("astro", `---\n---\n<p>hello</p>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_css", () => {
    // Smoke test: load css and parse a simple snippet
    if (!hasLanguage("css")) {
      console.log("Skipping: language 'css' not available");
      return;
    }
    const tree = parseString("css", `body { color: red; }`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_graphql", () => {
    // Smoke test: load graphql and parse a simple snippet
    if (!hasLanguage("graphql")) {
      console.log("Skipping: language 'graphql' not available");
      return;
    }
    const tree = parseString("graphql", `type Query { hello: String }`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_html", () => {
    // Smoke test: load html and parse a simple snippet
    if (!hasLanguage("html")) {
      console.log("Skipping: language 'html' not available");
      return;
    }
    const tree = parseString("html", `<p>hello</p>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_javascript", () => {
    // Smoke test: load javascript and parse a simple snippet
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const tree = parseString("javascript", `console.log('hello');`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_jsdoc", () => {
    // Smoke test: load jsdoc and parse a simple snippet
    if (!hasLanguage("jsdoc")) {
      console.log("Skipping: language 'jsdoc' not available");
      return;
    }
    const tree = parseString("jsdoc", `/** @param {string} name */`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_json", () => {
    // Smoke test: load json and parse a simple snippet
    if (!hasLanguage("json")) {
      console.log("Skipping: language 'json' not available");
      return;
    }
    const tree = parseString("json", `{\"key\": \"value\"}`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_prisma", () => {
    // Smoke test: load prisma and parse a simple snippet
    if (!hasLanguage("prisma")) {
      console.log("Skipping: language 'prisma' not available");
      return;
    }
    const tree = parseString("prisma", `model User { id Int @id }`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_scss", () => {
    // Smoke test: load scss and parse a simple snippet
    if (!hasLanguage("scss")) {
      console.log("Skipping: language 'scss' not available");
      return;
    }
    const tree = parseString("scss", `\$color: red;\nbody { color: \$color; }`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_svelte", () => {
    // Smoke test: load svelte and parse a simple snippet
    if (!hasLanguage("svelte")) {
      console.log("Skipping: language 'svelte' not available");
      return;
    }
    const tree = parseString("svelte", `<p>hello</p>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    freeTree(tree);
  });

  it("smoke_tsx", () => {
    // Smoke test: load tsx and parse a simple snippet
    if (!hasLanguage("tsx")) {
      console.log("Skipping: language 'tsx' not available");
      return;
    }
    const tree = parseString("tsx", `const App = () => <div />;`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_twig", () => {
    // Smoke test: load twig and parse a simple snippet
    if (!hasLanguage("twig")) {
      console.log("Skipping: language 'twig' not available");
      return;
    }
    const tree = parseString("twig", `{{ variable }}`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_typescript", () => {
    // Smoke test: load typescript and parse a simple snippet
    if (!hasLanguage("typescript")) {
      console.log("Skipping: language 'typescript' not available");
      return;
    }
    const tree = parseString("typescript", `const x: number = 42;`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_vue", () => {
    // Smoke test: load vue and parse a simple snippet
    if (!hasLanguage("vue")) {
      console.log("Skipping: language 'vue' not available");
      return;
    }
    const tree = parseString("vue", `<template><div>hello</div></template>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

});
