#ifndef TS_PACK_H
#define TS_PACK_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
/* Forward declaration for tree-sitter's TSLanguage type */
typedef struct TSLanguage TSLanguage;

/**
 * Opaque handle to a language registry.
 * Created with `ts_pack_registry_new` and freed with `ts_pack_registry_free`.
 */
typedef struct TsPackRegistry TsPackRegistry;

/**
 * Opaque handle to a parsed syntax tree.
 * Created with `ts_pack_parse_string` and freed with `ts_pack_tree_free`.
 */
typedef struct TsPackTree TsPackTree;

/**
 * Create a new language registry.
 *
 * Returns a pointer to the registry, or null on failure.
 * The caller must free the registry with `ts_pack_registry_free`.
 *
 * # Safety
 *
 * The returned pointer must be freed with `ts_pack_registry_free`.
 */
struct TsPackRegistry *ts_pack_registry_new(void);

/**
 * Free a registry previously created with `ts_pack_registry_new`.
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `registry` must be a pointer returned by `ts_pack_registry_new`, or null.
 */
void ts_pack_registry_free(struct TsPackRegistry *registry);

/**
 * Get a raw `TSLanguage` pointer for the given language name.
 *
 * Returns null on error (check `ts_pack_last_error` for details).
 * The returned pointer is valid for the lifetime of the registry.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 * `name` must be a valid null-terminated UTF-8 C string, or null.
 */
const TSLanguage *ts_pack_get_language(const struct TsPackRegistry *registry, const char *name);

/**
 * Return the number of available languages.
 *
 * Returns 0 if the registry pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 */
uintptr_t ts_pack_language_count(const struct TsPackRegistry *registry);

/**
 * Get the language name at the given index.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the index is out of bounds or
 * the registry pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 */
const char *ts_pack_language_name_at(const struct TsPackRegistry *registry, uintptr_t index);

/**
 * Check whether the registry contains a language with the given name.
 *
 * Returns false if the registry or name pointer is null.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`, or null.
 * `name` must be a valid null-terminated UTF-8 C string, or null.
 */
bool ts_pack_has_language(const struct TsPackRegistry *registry, const char *name);

/**
 * Detect language name from a file path.
 *
 * Returns a newly allocated null-terminated UTF-8 string with the language name,
 * or null if the extension is not recognized. The caller must free the returned
 * pointer with `ts_pack_free_string`.
 *
 * # Safety
 *
 * `path` must be a valid null-terminated UTF-8 C string, or null.
 */
char *ts_pack_detect_language(const char *path);

/**
 * Get the last error message, or null if no error occurred.
 *
 * The returned pointer is valid until the next FFI call on the same thread.
 * The caller must NOT free this pointer.
 *
 * # Safety
 *
 * The returned pointer is only valid until the next FFI call on the same thread.
 */
const char *ts_pack_last_error(void);

/**
 * Clear the last error.
 *
 * # Safety
 *
 * This function is always safe to call.
 */
void ts_pack_clear_error(void);

/**
 * Free a string that was returned by the FFI (e.g. from `ts_pack_language_name_at`).
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `s` must be a pointer returned by an FFI function in this crate, or null.
 */
void ts_pack_free_string(char *s);

/**
 * Parse a source string using the named language and return an opaque tree handle.
 *
 * Returns null on error (check `ts_pack_last_error` for details).
 * The caller must free the tree with `ts_pack_tree_free`.
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`.
 * `name` and `source` must be valid null-terminated UTF-8 C strings.
 */
struct TsPackTree *ts_pack_parse_string(const struct TsPackRegistry *registry,
                                        const char *name,
                                        const char *source,
                                        uintptr_t source_len);

/**
 * Free a tree previously created with `ts_pack_parse_string`.
 *
 * Passing a null pointer is a safe no-op.
 *
 * # Safety
 *
 * `tree` must be a pointer returned by `ts_pack_parse_string`, or null.
 */
void ts_pack_tree_free(struct TsPackTree *tree);

/**
 * Get the type name of the root node of the tree.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
char *ts_pack_tree_root_node_type(const struct TsPackTree *tree);

/**
 * Get the number of named children of the root node.
 *
 * Returns 0 if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
uint32_t ts_pack_tree_root_child_count(const struct TsPackTree *tree);

/**
 * Check whether any node in the tree has the given type name.
 *
 * Uses a depth-first traversal via TreeCursor.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 * `node_type` must be a valid null-terminated UTF-8 C string, or null.
 */
bool ts_pack_tree_contains_node_type(const struct TsPackTree *tree, const char *node_type);

/**
 * Check whether the tree contains any ERROR or MISSING nodes.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
bool ts_pack_tree_has_error_nodes(const struct TsPackTree *tree);

/**
 * Return the S-expression representation of the tree.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
char *ts_pack_tree_to_sexp(const struct TsPackTree *tree);

/**
 * Return the count of ERROR and MISSING nodes in the tree.
 *
 * Returns 0 if the tree pointer is null.
 *
 * # Safety
 *
 * `tree` must be a valid pointer returned by `ts_pack_parse_string`, or null.
 */
uintptr_t ts_pack_tree_error_count(const struct TsPackTree *tree);

/**
 * Process source code and extract metadata + chunks as a JSON C string.
 *
 * `config_json` is a null-terminated JSON string with fields:
 * - `language` (string, required): the language name
 * - `chunk_max_size` (number, optional): maximum chunk size in bytes (default: 1500)
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `registry` must be a valid pointer returned by `ts_pack_registry_new`.
 * `source` must be a valid pointer to `source_len` bytes.
 * `config_json` must be a valid null-terminated UTF-8 C string.
 */
char *ts_pack_process(const struct TsPackRegistry *registry,
                      const char *source,
                      uintptr_t source_len,
                      const char *config_json);

/**
 * Initialize the language pack with configuration.
 *
 * `config_json` is a null-terminated JSON string with optional fields:
 * - `cache_dir` (string): override default cache directory
 * - `languages` (array of strings): languages to pre-download
 * - `groups` (array of strings): language groups to pre-download
 *
 * Returns 0 on success, -1 on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `config_json` must be a valid null-terminated UTF-8 C string, or null.
 */
int32_t ts_pack_init(const char *config_json);

/**
 * Configure the language pack without downloading.
 *
 * `config_json` is a null-terminated JSON string with optional fields:
 * - `cache_dir` (string): override default cache directory
 *
 * Returns 0 on success, -1 on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `config_json` must be a valid null-terminated UTF-8 C string, or null.
 */
int32_t ts_pack_configure(const char *config_json);

/**
 * Download specific languages to the cache.
 *
 * `names` is an array of pointers to null-terminated language name strings.
 * `count` is the number of strings in the array.
 *
 * Returns the number of newly downloaded languages on success, or -1 on error.
 *
 * # Safety
 *
 * `names` must be a valid array of `count` pointers to null-terminated UTF-8 C strings.
 */
int32_t ts_pack_download(const char *const *names, uintptr_t count);

/**
 * Download all available languages from the remote manifest.
 *
 * Returns the number of newly downloaded languages on success, or -1 on error.
 *
 * # Safety
 *
 * This function is safe to call; it does not take any unsafe parameters.
 */
int32_t ts_pack_download_all(void);

/**
 * Get all language names available in the remote manifest.
 *
 * Returns a newly-allocated array of language name strings. The caller must
 * free the array with `ts_pack_free_string_array`, and the individual strings
 * with `ts_pack_free_string`.
 *
 * Sets `out_count` to the number of languages in the returned array.
 * Returns null on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * `out_count` must be a valid, non-null pointer to a `usize` that the caller owns.
 */
const char *const *ts_pack_manifest_languages(uintptr_t *out_count);

/**
 * Get all languages that are already downloaded and cached locally.
 *
 * Returns a newly-allocated array of language name strings. The caller must
 * free the array with `ts_pack_free_string_array`, and the individual strings
 * with `ts_pack_free_string`.
 *
 * Sets `out_count` to the number of languages in the returned array.
 * Returns null if the count pointer is null, but never fails otherwise.
 *
 * # Safety
 *
 * `out_count` must be a valid, non-null pointer to a `usize` that the caller owns.
 */
const char *const *ts_pack_downloaded_languages(uintptr_t *out_count);

/**
 * Delete all cached parser shared libraries.
 *
 * Returns 0 on success, -1 on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * This function is safe to call; it does not take any unsafe parameters.
 */
int32_t ts_pack_clean_cache(void);

/**
 * Get the effective cache directory path as a C string.
 *
 * Returns a newly-allocated C string that the caller must free with
 * `ts_pack_free_string`. Returns null on error (check `ts_pack_last_error`).
 *
 * # Safety
 *
 * This function is safe to call; it does not take any unsafe parameters.
 */
char *ts_pack_cache_dir(void);

/**
 * Free a string array that was returned by the FFI (e.g. from `ts_pack_manifest_languages`).
 *
 * Passing a null pointer is a safe no-op.
 * This function only frees the array wrapper, not the individual strings.
 * Use `ts_pack_free_string` on each individual string before calling this.
 *
 * # Safety
 *
 * `arr` must be a pointer returned by an FFI function in this crate that returns
 * an array, or null. Individual strings must be freed first with `ts_pack_free_string`.
 */
void ts_pack_free_string_array(const char **arr);

#endif  /* TS_PACK_H */
