// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestParsingJavascriptClass(t *testing.T) {
	// Parse a JavaScript class declaration.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestParsingPythonFunction(t *testing.T) {
	// Parse a Python function definition.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestParsingRustStruct(t *testing.T) {
	// Parse a Rust struct definition.
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	ptr, err := reg.GetLanguage("rust")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "rust", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "rust")
	}
}
